### ISSUE TITLE
请问会支持代理吗？

### ISSUE THREAD

**Issue by Fstark-prog** [RapidDNS/Afuzz#4]
类似的路径探测行为，是否能够支持走代理？

**Comment by RapidDNS** [comment]
> 类似的路径探测行为，是否能够支持走代理？

No problem

**Comment by RapidDNS** [comment]
> 类似的路径探测行为，是否能够支持走代理？

use --proxy or -p 

--proxy http://127.0.0.1:8080

**Comment by Fstark-prog** [comment]
开启代理后多次显示如下错误，关闭代理即可正常运行：
![image](https://github.com/RapidDNS/Afuzz/assets/30889092/595c57c2-0030-45ea-b4e0-e70586214c63)

`Traceback (most recent call last):
  File "/config/workspace/Afuzz/afuzz/lib/fuzzer.py", line 311, in start
    await asyncio.gather(*all_process)
  File "/config/workspace/Afuzz/afuzz/lib/fuzzer.py", line 229, in consume
    await self.check_vuln(resp, url, path, depth, target=target["target"])
  File "/config/workspace/Afuzz/afuzz/lib/fuzzer.py", line 62, in check_vuln
    result_404 = self.check_404_page(response)
  File "/config/workspace/Afuzz/afuzz/lib/fuzzer.py", line 390, in check_404_page
    elif self.dot_404.status == response.status and self.dot_404.md5(temp2_404) == response.md5(temp_page):
AttributeError: 'NoneType' object has no attribute 'status'`

**Comment by Fstark-prog** [comment]
经测试get_404_page过程走代理会导致此问题，修改代码该部分走本地后已解决
